// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZtpv8E5lf7fNXhgHnvhBTiOcn_S4HavI',
    appId: '1:125791679910:web:fb80cf66edbaeeb509cb67',
    messagingSenderId: '125791679910',
    projectId: 'cards-english',
    authDomain: 'cards-english.firebaseapp.com',
    storageBucket: 'cards-english.appspot.com',
    measurementId: 'G-5PKMQEL15G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkL_TNqcLXpCsGh-drQshdygNU6M8JVSM',
    appId: '1:125791679910:android:8ca9d4e30a1a25fb09cb67',
    messagingSenderId: '125791679910',
    projectId: 'cards-english',
    storageBucket: 'cards-english.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLVxi420r1k3_BXz74cmhFGdEan1v9GtQ',
    appId: '1:125791679910:ios:46c0a2c2a3eb11ee09cb67',
    messagingSenderId: '125791679910',
    projectId: 'cards-english',
    storageBucket: 'cards-english.appspot.com',
    iosBundleId: 'com.example.cardsEnglish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLVxi420r1k3_BXz74cmhFGdEan1v9GtQ',
    appId: '1:125791679910:ios:46c0a2c2a3eb11ee09cb67',
    messagingSenderId: '125791679910',
    projectId: 'cards-english',
    storageBucket: 'cards-english.appspot.com',
    iosBundleId: 'com.example.cardsEnglish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZtpv8E5lf7fNXhgHnvhBTiOcn_S4HavI',
    appId: '1:125791679910:web:819904c9ff23f94709cb67',
    messagingSenderId: '125791679910',
    projectId: 'cards-english',
    authDomain: 'cards-english.firebaseapp.com',
    storageBucket: 'cards-english.appspot.com',
    measurementId: 'G-E2KVQQSP4F',
  );
}
